# Generated by Django 3.1.7 on 2021-04-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20210401_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='image_url',
        ),
        migrations.AddField(
            model_name='topping',
            name='photo',
            field=models.ImageField(default='defo', upload_to='images/'),
        ),
    ]
