# Generated by Django 3.1.7 on 2021-04-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_auto_20210401_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='photo',
        ),
        migrations.AddField(
            model_name='topping',
            name='image_url',
            field=models.CharField(blank=True, max_length=2083),
        ),
    ]
