# Generated by Django 3.1.7 on 2021-04-05 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_auto_20210401_1225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
