# Generated by Django 3.1.7 on 2021-04-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0009_auto_20210405_1852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProperOrder',
        ),
    ]
